### ISSUE TITLE
Update Required for microdesign/catalogpricerulesapi to Support magento 2.4.7-p3

### ISSUE THREAD

**Issue by anasshl** [kayintveen/Microdesign_CatalogPriceRulesApi#1]
Hello,

I am experiencing a compatibility issue while trying to install the microdesign/catalogpricerulesapi module with Composer.

When running the following command:

```php
composer require microdesign/catalogpricerulesapi --ignore-platform-reqs
``` 

I encounter the following error:

```php
Problem 1
    - microdesign/catalogpricerulesapi dev-main requires magento/module-catalog-rule 101.2.6 -> found magento/module-catalog-rule[101.2.6] but the package is fixed to 101.2.7 (lock file version) by a partial update and that version does not match.

``` 

It seems that the microdesign/catalogpricerulesapi module requires version 101.2.6 of magento/module-catalog-rule, but my project is using 101.2.7, which is causing the installation to fail.

Could you please consider updating the microdesign/catalogpricerulesapi module to support Magento 2.4.7-p3? This would greatly enhance compatibility with current Magento installations and improve the overall usability of the module.

Thank you for your attention to this matter!

Best regards,

**Comment by kayintveen** [comment]
Thanks module has not been updated for a while indeed.
ill change.

**Comment by kayintveen** [comment]
Done!
